export {
  DEFAULT_HUNT_COOLDOWN_SECONDS,
  DEFAULT_SMUDGE_SECONDS,
  DEMON_SMUDGE_SECONDS,
  HUNT_COOLDOWN_DURATION_PRESETS,
  SMUDGE_DURATION_PRESETS,
  SPIRIT_SMUDGE_SECONDS,
  createIdleTimer,
  getElapsedSeconds,
  getTimerPhase,
  isTimerActive,
  isTimerRunning,
  resetTimer,
  setTimerDuration,
  startTimer,
  toggleTimer,
} from "./timerState";
